<?php
$siteTitle = '16 Clans Katutubong Blaan';
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="The official cultural and community information platform of 16 Clans Katutubong Blaan in Bagong Pag-asa Tribal Community.">
	<title><?= htmlspecialchars($siteTitle) ?> | Culture, Heritage & Community</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<a class="skip-link" href="#main-content">Skip to content</a>
	<header class="site-header">
		<div class="topbar"><div class="container topbar-inner"><span>Bagong Pag-asa Tribal Community</span><span>Brgy. Sinawal, General Santos City</span></div></div>
		<div class="container nav-wrap">
			<a class="brand" href="#home" aria-label="16 Clans Katutubong Blaan home"><span class="brand-mark">16</span><span><strong>Clans</strong><small>Katutubong Blaan</small></span></a>
			<button class="menu-toggle" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span><b class="sr-only">Open menu</b></button>
			<nav id="site-nav" class="site-nav" aria-label="Main navigation">
				<a class="active" href="#home">Home</a><a href="#about">About the Tribe</a><a href="#clans">16 Clans</a><a href="#culture">Culture & Traditions</a><a href="#history">History & Heritage</a><a href="#domain">Ancestral Domain</a><a href="#governance">Tribal Governance</a><a href="#programs">Community Programs</a><a href="#gallery">Gallery</a><a href="#news">News & Announcements</a><a href="#knowledge">Cultural Knowledge Center</a><a href="#livelihood">Indigenous Products & Livelihood</a><a href="#events">Events</a><a href="#documents">Documents</a><a href="#contact">Contact</a>
			</nav>
		</div>
	</header>

	<main id="main-content">
		<section id="home" class="hero">
			<div class="hero-image"></div><div class="hero-shade"></div>
			<div class="container hero-content"><p class="eyebrow light">Sfalunam ded Tu-a de Muna</p><h1>16 Clans<br><em>Katutubong Blaan</em></h1><p class="hero-tagline">Preserving Culture, Protecting Heritage, Strengthening Community</p><a class="button button-gold" href="#about">Discover our story <span>→</span></a></div>
			<div class="hero-note"><span class="line"></span><span>Our roots run deep. Our future is shared.</span></div>
		</section>

		<section id="about" class="welcome section"><div class="container two-col"><div><p class="eyebrow">Welcome to our home</p><h2>A living culture, carried forward together.</h2></div><div class="intro-copy"><p>We are the 16 Clans Katutubong Blaan of Bagong Pag-asa Tribal Community, a community rooted in kinship, stewardship, and the enduring wisdom of our ancestors.</p><p>This platform is a shared space for our people and guests to learn about Blaan identity, celebrate our living traditions, and support the work of protecting our heritage for generations to come.</p><a class="text-link" href="#history">Read our history <span>↗</span></a></div></div></section>

		<section class="vision-mission"><div class="container vm-grid"><article><span class="number">01</span><h3>Our Vision</h3><p>A self-determined, united, and empowered Blaan community where culture is honored, ancestral domain is protected, and every generation thrives.</p></article><article><span class="number">02</span><h3>Our Mission</h3><p>To preserve Blaan heritage, strengthen traditional governance, nurture community well-being, and build a sustainable future through collective action.</p></article><div class="woven-stamp">BLAAN<br><small>living heritage</small></div></div></section>

		<section id="culture" class="section culture-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Our living heritage</p><h2>Culture & Traditions</h2></div><p>Knowledge lives in the hands, voices, and everyday practices of our people.</p></div><div class="culture-grid"><article class="culture-card large"><img src="photo/b2.jpg" alt="Community members sharing a meal outdoors"><div><span>Community</span><h3>Kinship is our first language</h3></div></article><article class="culture-card"><img src="photo/b3.jpg" alt="Colorful handwoven textile detail"><div><span>Craft</span><h3>Weaving stories into every thread</h3></div></article><article class="culture-card"><img src="photo/b4.jpg" alt="Green forest landscape and mountain valley"><div><span>Stewardship</span><h3>Land as memory and responsibility</h3></div></article></div></div></section>

		<section id="clans" class="section clans-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Our kinship map</p><h2>The 16 Clans</h2></div><p>Each clan carries a distinct story. Together, we form one community.</p></div><div class="clan-list"><div class="clan-item"><b>01</b><span>Fraidelyn</span><small>Representative</small></div><div class="clan-item"><b>02</b><span>Samal</span><small>Representative</small></div><div class="clan-item"><b>03</b><span>Dani</span><small>Representative</small></div><div class="clan-item"><b>04</b><span>Faid</span><small>Representative</small></div><div class="clan-item"><b>05</b><span>Fuhuli</span><small>Representative</small></div><div class="clan-item"><b>06</b><span>Balung</span><small>Representative</small></div><div class="clan-item"><b>07</b><span>Adal</span><small>Representative</small></div><div class="clan-item"><b>08</b><span>Labi</span><small>Representative</small></div><div class="clan-item"><b>09</b><span>Fadul</span><small>Representative</small></div><div class="clan-item"><b>10</b><span>Flaran</span><small>Representative</small></div><div class="clan-item"><b>11</b><span>Fandang</span><small>Representative</small></div><div class="clan-item"><b>12</b><span>Fungko</span><small>Representative</small></div><div class="clan-item"><b>13</b><span>Fagel</span><small>Representative</small></div><div class="clan-item"><b>14</b><span>Falah</span><small>Representative</small></div><div class="clan-item"><b>15</b><span>Fasig</span><small>Representative</small></div><div class="clan-item"><b>16</b><span>Fumag</span><small>Representative</small></div></div></div></section>

		<section id="governance" class="leader-section"><div class="container leader-grid"><div class="leader-photo"><img src="photo/b1.jpg" alt="Community leader portrait"><span class="photo-label">Leadership & service</span></div><div class="leader-copy"><p class="eyebrow">Our traditional leadership</p><h2>Guided by wisdom.<br><em>Rooted in service.</em></h2><p class="quote">“Leadership is a promise to listen, to protect, and to leave a stronger community for those who come after us.”</p><h3>Bai Libun Labeh Fraidelyn Samal Dani</h3><p class="role">16 Clans Chieftain <span>·</span> Sfalunam ded Tu-a de Muna</p><p>Our tribal governance is grounded in customary law, consultation, respect for elders, and the collective voice of our clans.</p><a class="text-link light-link" href="#contact">Connect with tribal leadership <span>↗</span></a></div></div></section>

		<section id="programs" class="section programs"><div class="container"><div class="section-heading"><div><p class="eyebrow">Building tomorrow</p><h2>Community Programs</h2></div><a class="text-link" href="#contact">Support our work <span>↗</span></a></div><div class="program-grid"><a href="#contact"><span>01</span><h3>Cultural Preservation</h3><p>Keeping language, arts, and customary knowledge alive.</p></a><a href="#contact"><span>02</span><h3>Self-Governance</h3><p>Strengthening participatory leadership and customary law.</p></a><a href="#domain"><span>03</span><h3>Ancestral Domain Protection</h3><p>Defending land, waters, and the right to self-determination.</p></a><a href="#livelihood"><span>04</span><h3>Livelihood Programs</h3><p>Creating dignified, culture-based opportunities.</p></a><a href="#contact"><span>05</span><h3>Youth Development</h3><p>Equipping the next generation to lead with pride.</p></a><a href="#contact"><span>06</span><h3>Women’s Empowerment</h3><p>Honoring women’s leadership, voice, and enterprise.</p></a><a href="#contact"><span>07</span><h3>Tribal Justice System</h3><p>Resolving community concerns through customary practice.</p></a><a href="#domain"><span>08</span><h3>Environmental Protection</h3><p>Protecting the living ecosystems that sustain us.</p></a></div></div></section>

		<section id="domain" class="domain-section"><div class="domain-image"></div><div class="domain-content"><p class="eyebrow light">Our sacred responsibility</p><h2>Ancestral Domain</h2><p>Our ancestral domain is more than territory. It is the home of our stories, the source of our sustenance, and a trust we carry for future generations.</p><div class="domain-facts"><div><strong>16</strong><span>Clans united</span></div><div><strong>∞</strong><span>A heritage without end</span></div></div><a class="button button-outline" href="#documents">Explore resources <span>→</span></a></div></section>

		<section id="history" class="section history"><div class="container history-grid"><div><p class="eyebrow">From then to now</p><h2>History & Heritage</h2><p>From our ancestors’ journeys to the community we shape today, the Blaan story is one of resilience, creativity, and belonging.</p><a class="text-link" href="#knowledge">Visit the knowledge center <span>↗</span></a></div><div class="timeline"><div><b>Before memory</b><p>Our ancestors establish relationships with the land and each other.</p></div><div><b>Living traditions</b><p>Customary law, weaving, music, and oral history carry knowledge across generations.</p></div><div><b>Today & beyond</b><p>The 16 Clans come together to protect identity and build a shared future.</p></div></div></div></section>

		<section id="gallery" class="section gallery"><div class="container"><div class="section-heading"><div><p class="eyebrow">Seen through our eyes</p><h2>Community Gallery</h2></div><a class="text-link" href="#contact">Share your story <span>↗</span></a></div><div class="gallery-grid"><img src="photo/a1.jpg" alt="People working together in a community garden"><img src="photo/a4.jpg" alt="Lush tropical landscape"><img src="photo/a3.jpg"><img src="photo/a2.jpg" alt="Young people gathering outdoors"></div></div></section>

		<section id="news" class="section news"><div class="container"><div class="section-heading"><div><p class="eyebrow">Stay connected</p><h2>News & Announcements</h2></div><a class="text-link" href="#contact">View all updates <span>↗</span></a></div><div class="news-grid"><article><div class="news-date"><strong>18</strong><span>SEP<br>2026</span></div><div><span class="category">Community</span><h3>16 Clans convene for annual cultural planning assembly</h3><a href="#contact">Read story →</a></div></article><article><div class="news-date"><strong>04</strong><span>SEP<br>2026</span></div><div><span class="category">Youth</span><h3>Young Blaan leaders begin heritage documentation workshop</h3><a href="#contact">Read story →</a></div></article><article><div class="news-date"><strong>22</strong><span>AUG<br>2026</span></div><div><span class="category">Livelihood</span><h3>Community makers’ collection opens for local orders</h3><a href="#livelihood">Read story →</a></div></article></div></div></section>

		<section id="knowledge" class="resources"><div class="container resource-grid"><div><p class="eyebrow light">Learn with care</p><h2>Cultural Knowledge Center</h2><p>Explore resources created with community guidance: oral histories, Blaan words, customary practices, and learning materials.</p><a class="button button-gold" href="#documents">Browse resources <span>→</span></a></div><div class="resource-list"><a href="#documents"><span>↗</span><div><b>Blaan language & words</b><small>A growing community glossary</small></div></a><a href="#documents"><span>↗</span><div><b>Living traditions guide</b><small>Learn from culture bearers</small></div></a><a href="#documents"><span>↗</span><div><b>Oral histories archive</b><small>Voices across generations</small></div></a></div></div></section>

		<section id="livelihood" class="section livelihood"><div class="container two-col"><div><p class="eyebrow">Made with meaning</p><h2>Indigenous Products & Livelihood</h2></div><div><p>Every woven piece, craft, and harvest reflects skill, patience, and a relationship with place. Support community makers and help culture-based livelihoods flourish.</p><a class="text-link" href="#contact">Inquire about products <span>↗</span></a></div></div></section>
		<section id="events" class="events-section"><div class="container event-grid"><div><p class="eyebrow">Mark your calendar</p><h2>Upcoming Events</h2></div><div class="event-item"><div class="event-date"><strong>12</strong><span>OCT<br>2026</span></div><div><span class="category">Community gathering</span><h3>16 Clans Cultural Day</h3><p>Bagong Pag-asa Tribal Community</p></div><a href="#contact" aria-label="Learn about 16 Clans Cultural Day">↗</a></div><div class="event-item"><div class="event-date"><strong>08</strong><span>NOV<br>2026</span></div><div><span class="category">Learning circle</span><h3>Youth & Elders Knowledge Exchange</h3><p>Community Learning House</p></div><a href="#contact" aria-label="Learn about Youth and Elders Knowledge Exchange">↗</a></div></div></section>
		<section id="documents" class="section documents"><div class="container"><div class="section-heading"><div><p class="eyebrow">Open community records</p><h2>Documents</h2></div><p>Public information and resources for community members and partners.</p></div><div class="document-list"><a href="documents/example-community-profile.php" download="16-clans-community-profile.pdf"><span class="file-icon">PDF</span><div><b>16 Clans Community Profile</b><small>Community information · 2026</small></div><strong>↓</strong></a><a href="documents/example-community-profile.php" download="community-programs-overview.pdf"><span class="file-icon">PDF</span><div><b>Community Programs Overview</b><small>Program brief · 2026</small></div><strong>↓</strong></a><a href="documents/example-community-profile.php" download="partner-visitor-protocol.pdf"><span class="file-icon">PDF</span><div><b>Partner & Visitor Protocol</b><small>Community guide · 2026</small></div><strong>↓</strong></a></div></div></section>
		<section id="contact" class="contact-section"><div class="container contact-grid"><div><p class="eyebrow light">Walk with us</p><h2>Let’s build a future that remembers.</h2><p>For community inquiries, cultural learning visits, partnerships, and program support, reach out to the 16 Clans community.</p></div><div class="contact-details"><div><span>Visit</span><p>Bagong Pag-asa Tribal Community<br>Brgy. Sinawal, General Santos City</p></div><div><span>Email</span><p><a href="mailto:hello@16clansblaan.org">hello@16clansblaan.org</a></p></div><div><span>Social</span><p><a href="#contact">Facebook community page ↗</a></p></div></div></div></section>
	</main>
	<footer class="site-footer"><div class="container footer-main"><a class="brand footer-brand" href="#home"><span class="brand-mark">16</span><span><strong>Clans</strong><small>Katutubong Blaan</small></span></a><p>A shared home for Blaan heritage, community, and the generations ahead.</p><div class="footer-links"><a href="#about">About</a><a href="#culture">Culture</a><a href="#contact">Contact</a></div></div><div class="container footer-bottom"><span>© <?= date('Y') ?> 16 Clans Katutubong Blaan</span><span>Culture is a living responsibility.</span></div></footer>
	<script>const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});document.querySelectorAll('.site-nav a').forEach(link=>link.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');nav.classList.remove('open')}));</script>
</body>
</html>
